### ISSUE TITLE
Docker build failing for the past month

### ISSUE THREAD

**Issue by dolphinkite** [pducharme/UniFi-Video-Controller#1]
Hi,

I've successfully been using this docker image on my Synology NAS for the past months. However, I recently saw the 3.6 update to the unifi video controller and wanted to update my docker container. I noticed that since 1 month ago, the automated build for this docker container has been failing.

Is there any plant to update the docker image to the latest 3.6 controller?

Thanks for maintaining this.

**Comment by dolphinkite** [comment]
Additionally, the automated build's log states: 

> Build failed: The command '/bin/sh -c apt-get install -y ca-certificates-java fontconfig-config fonts-dejavu-core java-common jsvc libasyncns0 libavahi-client3 libavahi-common-data libavahi-common3 libcommons-daemon-java libcups2 libflac8 libfontconfig1 libfreetype6 libjpeg-turbo8 libjpeg8 liblcms2-2 libnspr4 libnss3 libnss3-nssdb libogg0 libpcsclite1 libpulse0 libsctp1 libsndfile1 libvorbis0a libvorbisenc2 libxau6 libxcb1 libxdmcp6 lksctp-tools mongodb-10gen openjdk-8-jre-headless tzdata-java --force-yes' returned a non-zero code: 100

**Comment by dolphinkite** [comment]
Ça semble réglé, Merci.

**Comment by pducharme** [comment]
Oui, j'ai mis à jour et ca fonctionne!
