### ISSUE TITLE
Unable to view live view, record, or set the record setting on camera

### ISSUE THREAD

**Issue by PoLoMoTo** [pducharme/UniFi-Video-Controller#109]
I am at a complete loss as to what I am doing wrong.  I had a container running with the camera a week ago to test and it worked perfectly.  This week I upgraded to 3.9.8 and set the folder paths for a secondary hard drive I had purchased for the recordings and now I'm having the issues in the title and Unifi Video doesn't show anything of use in the logs other than some connection stuff.  I changed the paths back to where they were before, changed the folder permissions to 777, redownloaded 3.9.7, every single time I got the same issue.  The camera seems to be working just fine it gets added just fine but when you go to live view theres a message at the top saying "Unable to load UVC G3 livestream."  The last recording for the camera is "n/a" but when you set the recording to full time it doesn't record and if I refresh the page it goes back to none instead of full time.

Does anyone have any idea what I could be doing wrong? I'm completely lost...

This is my docker run line:
`docker run -d --restart always --name unifi-video --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH -p 10001:10001 -p 1935:1935 -p 6666:6666 -p 7080:7080 -p 7442:7442 -p 7443:7443 -p 7444:7444 -p 7445:7445 -p 7446:7446 -p 7447:7447 -v /mnt/storage/Videos/unifi-video:/var/lib/unifi-video -v /mnt/storage/Videos/videos:/var/lib/unifi-video/videos -e TZ=America/New_York -e PUID=99 -e PGID=100 -e DEBUG=1 pducharme/unifi-video-controller`

**Comment by Saik0Shinigami** [comment]
Considering all the changing you did you might need to readopt the cameras.
I've had similar rollback issues in the past that required me going around
and factory resetting each camera before things worked them selves out.

-This message was sent from my phone.

**Comment by PoLoMoTo** [comment]
Yea I figured, that was the first thing I did actually.  I apologize I should have mentioned that, was still smashing my face on my keyboard when I posted that.

I had upgraded and switched to the new harddrive remotely via SSH since I wasn't home for the week and I had unplugged the camera before I left because it was only plugged in for testing so I couldn't unmanage it before upgrading.  When I got home today I factory reset the camera with the button on the back and added it back no problem.  Thats where my issues started.  I did reset or unmanage the camera between upgrades/downgrades/image changes, and rolled back the firmware version for Unifi Video 3.9.7 since 3.9.8 had upgraded the camera automatically.

**Comment by PoLoMoTo** [comment]
Yea I figured, that was the first thing I did actually.  I apologize I should have mentioned that, was still smashing my face on my keyboard when I posted that.

I had upgraded and switched to the new harddrive remotely via SSH since I wasn't home for the week and I had unplugged the camera before I left because it was only plugged in for testing so I couldn't unmanage it before upgrading.  When I got home today I factory reset the camera with the button on the back and added it back no problem.  Thats where my issues started.  I did reset or unmanage the camera between upgrades/downgrades/image changes, and rolled back the firmware version for Unifi Video 3.9.7 since 3.9.8 had upgraded the camera automatically.

**Comment by PoLoMoTo** [comment]
Sorry I apparently had a stroke or something and closed this.  Today is not my day...

**Comment by fryfrog** [comment]
Could the container be telling the cameras its 172 address when it should be a real IP?

**Comment by PoLoMoTo** [comment]
Ok so the problem was that I didn't realize Firefox wasn't supported. The computer I tested it on the first time used Chrome and the second one had Firefox. I feel like the web app should warn you if it detects you're using Firefox but that's out of the scope of this project. Thanks for the help, as usual it was just me being a dumb dumb.

**Comment by fryfrog** [comment]
Dang, *I* didn't even realize Firefox wasn't supported. That is super lame. :/
