### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by alexanderpem** [pducharme/UniFi-Video-Controller#111]
Hi,

sorry but can you say me how i can update the server from 3.9.7 to 3.9.9 with your script? :-) Thank you very much

**Comment by fryfrog** [comment]
It is a docker image, so just the standard way you do that w/ your setup. For example, I `docker pull` and then restart my container.

There are many ways of running them, so it'll depend on your setup.

**Comment by fryfrog** [comment]
I don't either buddy, you're gonna have to learn how what ever you use intends you to do it. All I know is that as a CLI user, I just `docker pull` to update. If you're on unRAID, it probably has some mechanism you're supposed to use. Similar on Synology too, maybe.
