### ISSUE TITLE
Versions....

### ISSUE THREAD

**Issue by kevsterd** [pducharme/UniFi-Video-Controller#116]
I see the Dockerfile on here has been updated, but the version on Dockerhub used for a pull is still showing a beta version.

Whats the trigger ?

**Comment by christiananguiano** [comment]
It looks like the automated builds in Docker Hub didn't get triggered after updating the github repo. I believe 3.9.11 is currently the latest stable version but Docker hub still has 3.9.9 as its latest stable version.

**Comment by stefancrain** [comment]
```
$ docker pull pducharme/unifi-video-controller:latest
latest: Pulling from pducharme/unifi-video-controller
Digest: sha256:b0fcdb84584fae39d28f47948bf1e824e2222835733d262886da1cda0bfbd323
Status: Image is up to date for pducharme/unifi-video-controller:latest

$ docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}'  pducharme/unifi-video-controller:latest
...
version=3.9.9
```

Currently the [stable release](https://www.ubnt.com/download/unifi-video/unifi-nvr/) available for download is 3.9.11

As @christiananguiano said, the confusing part is that the docker file was updated 8 days ago but it didn't seem to trigger a push to dockerhub.

**Comment by x2on** [comment]
@pducharme please update the docker hub repo tag to 3.9.11

**Comment by depasseg** [comment]
Please trigger the Docker hub "latest" build.  It's stuck on 3.9.9.

**Comment by pducharme** [comment]
Hi,

Latest should now be 3.9.11. I dont Know how to create a tag in github for 3.9.11, but Latest has it now,

Envoyé de mon iPad

**Comment by depasseg** [comment]
Hmm, after docker pull, docker inspect shows 3.9.11, but the GUI shows 3.9.9.  Anyone else experiencing this?

**Comment by pducharme** [comment]
Sent you an invite on github 

Envoyé de mon iPad

**Comment by stefancrain** [comment]
3.9.11 has been released to docker hub 
https://hub.docker.com/r/pducharme/unifi-video-controller/tags/

**Comment by pducharme** [comment]
Was it automatic? Or did you had to do any action? 

Envoyé de mon iPad

**Comment by stefancrain** [comment]
@pducharme If I were trying to reverse engineer what happens in this project (can't see the setup in docker hub) I would guess that these Autobuild Tags exist: 
- Beta = Beta branch
- Latest = Release branch
- Tags = tagged versions from release (hopefully)

![image](https://user-images.githubusercontent.com/330720/48730648-05256e00-ec09-11e8-845e-8029bf636b50.png)

I created a `3.9.11` tag from the `release` branch and pushed to github, the build happened automatically after that.

**Comment by pducharme** [comment]
"I created a 3.9.11 tag from the release branch and pushed to github, the build happened automatically after that."

That is the part i dont Know how to do.  I dont use any local IDE or developpement software, just the github Website. Can i do that from there?

Envoyé de mon iPad

**Comment by stefancrain** [comment]
@pducharme ah yes, here are the instructions to push from the webui https://help.github.com/articles/creating-releases

**Comment by pducharme** [comment]
Ok thanks!

Envoyé de mon iPhone

**Comment by stefancrain** [comment]
I was able to verify in the webui that the version is 3.9.11, closing.
