### ISSUE TITLE
Pull from Github broken again....

### ISSUE THREAD

**Issue by kevsterd** [pducharme/UniFi-Video-Controller#119]
The Docker Hub image is stuck on 3.9.11 when 3.9.12 is latest on GitHub

**Comment by evanrich** [comment]
3.10 versions are missing from here as well.

**Comment by kevsterd** [comment]
Yeh.  Its what happened last time.  The automated push from Git appears to be broken for some reason.   Even though there is not much added in .10/.11/.12 I like to keep it up to date when testing. 

Perhaps more have migrated over to Protect (I doubt it) and so no one has noticed it stuck...

**Comment by ruimarinho** [comment]
I am following this as well and I tend to update often to avoid major upgrades.

**Comment by evanrich** [comment]
~_~  One thing about open source/community produced...is you're not guaranteed updates.
@kevsterd  @ruimarinho  if you are interested in 3.10.0 beta3, I just built it myself:

evanrich/unifi-video-controller:3.10.0-beta3

https://cloud.docker.com/repository/docker/evanrich/unifi-video-controller/general

YMMV, I had to take out the unifi-video.patch because I couldn't get it to successfully patch, hunks failed, so I changed the docker build to use "sed" to replace the contents instead.  Just deployed over 3.10.0 beta2 and so far everything seems to be working.

**Comment by kevsterd** [comment]
> One thing about open source/community produced...is you're not guaranteed updates.
@kevsterd @ruimarinho if you are interested in 3.10.0 beta3, I just built it myself:

Yep understood.  Just a shame when a great effort dosen't get maintained.   Yep, I know everyone is busy and its a low priority.  This project was seen as a successor to the last one that suffered the same issues.  Sad to see.

**Comment by geekofweek** [comment]
I think it might be an issue with the release branch not getting updated, I think that might be what the docker auto-build is looking at.

**Comment by domodial** [comment]
hello, 

I still can not download version 3.9.12 by this way pducharme / unifi-video-controller: 3.9.12 
why ?

**Comment by fryfrog** [comment]
Sorry for the delay, I don't get notifications for issues and just totally forgot about getting 3.9.12 to release after I tested it on my system. :(

**Comment by fryfrog** [comment]
I generally run it for a few days and then promote it. The tags let people roll back if it doesn't work and the Unifi people clearly think it is ready. I don't think it needs a *lot* of testing. I just totally dropped the promotion ball for a variety of reasons. :)

**Comment by fryfrog** [comment]
Humm, but Docker Hub isn't updating :/

**Comment by stefancrain** [comment]
@fryfrog I saw that as well, the tag should kick it off!

**Comment by stefancrain** [comment]
@fryfrog https://status.docker.com/

**Comment by cwhits** [comment]
it's been two days and docker hub hasn't updated. were builds down at the time that @fryfrog tagged 3.9.12? is there a way to kick it off manually?

**Comment by fryfrog** [comment]
I pushed another commit to `release`, deleted the tag and re-created it pointed at the dummy commit instead. I still don't see any activity on Docker Hub.

@pducharme: I don't have admin access to your hub, you're going to have to poke this w/ a stick.

**Comment by pducharme** [comment]
I triggered the docker build.

**Comment by fryfrog** [comment]
Can you trigger it for the 3.9.12 tag too?

**Comment by pducharme** [comment]
There is no tag 3.9.12 on docker hub, donis create one?

**Comment by domodial** [comment]
Unable to find image 'pducharme/unifi-video-controller:3.9.12' locally
docker: Error response from daemon: manifest for pducharme/unifi-video-controller:3.9.12 not found.

**Comment by fryfrog** [comment]
The linking should be fixed now and I've asked @pducharme to see if the 3.9.12 tag can be triggered. The 3.10.1 build is coming soon too, it is in `:beta` and `:testing` right now.
