### ISSUE TITLE
Streaming broken without using net=host

### ISSUE THREAD

**Issue by anstosa** [pducharme/UniFi-Video-Controller#122]
If I don't use the `net=host` option, the streaming URLs for RSTP etc use the docker IP and do not work with the host IP regardless of whether the correct ports are mapped. Changing it to `net=host` and everything works perfectly. Is there any way to tell the UniFi Video controller about it's external IP?

**Comment by fryfrog** [comment]
Streaming works "fine" for me w/o host network option. Are you *sure* you have all the ports forwarded? The IP is obviously wrong in the UI, you'll have to change that where ever you're using it to the ip of the server.

You could also try that networking mode that gives it its *own* IP.

This is my [unifi-video.service](https://ptpb.pw/myJn) file w/ my `docker run` command including *all* the port forwards (there are so many!).

I use streaming via the web site, via their iOS and Android apps and also on my Echo Show/Dot.

**Comment by fryfrog** [comment]
See #110 for details on macvlan or whatever it is called.

**Comment by anstosa** [comment]
Here's my `docker-compose.yml`. It's totally plausible that I messed something else up but I have all the ports you listed (and one you didn't). And yes I was replacing the IP in the UI with the server's actual IP. I assumed the reason it wasn't working was that it was doing some host-checking on the stream request and wasn't serving it because it didn't match'

```
---
version: "3"
services:
  unifi:
    image: pducharme/unifi-video-controller:latest
    container_name: nvr
    security_opt:
      - apparmor:unconfined
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
      - DEBUG=1
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    network_mode: host
    volumes:
      - config:/var/lib/unifi-video
      - storage:/var/lib/unifi-video/videos
    ports:
      - 10001:10001
      - 1935:1935
      - 6666:6666
      - 7004:7004
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
    restart: unless-stopped
volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs,rw,nolock
      device: ":/storage/nvr/"
  storage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs,rw,nolock
      device: ":/storage/nvr-storage/"
```

**Comment by fryfrog** [comment]
The rtsp link includes the port needed and you say you're doing the same as me, so it can't really be that. What are you using to test the rtsp stream? I'd probably experiment w/ VLC on some computer on the same LAN. Or just try setting it up w/ the macvlan thing, that'll probably solve it entirely. I should probably move my setup to that and then change the documentation to use that. Nobody doesn't not like the camera auto dection not working. :/

**Comment by anstosa** [comment]
I was testing with [Restreamer](https://datarhei.github.io/restreamer/). macvlan is interesting. I'll look at that!

I didn't test thoroughly with VLC (the docker host is isolated on a subnet with no other hosts which may complicate things too). If it's working for you then I'll just close this. The `net=host` hack doesn't really bother me for now.
