### ISSUE TITLE
Add 3.9.12 tag

### ISSUE THREAD

**Issue by viertaxa** [pducharme/UniFi-Video-Controller#123]
Please add a 3.9.12 tag to the image on dockerhub. 

Thanks!

**Comment by fryfrog** [comment]
The tag is there in github, but the link was messed up. I've asked @pducharme to try and trigger a build for the 3.9.12 tag.

But 3.10.1 is out and I'll make it `:latest` soon, so it may not matter.

**Comment by viertaxa** [comment]
3.10.1 is FUBAR for me, any chance of getting the tag @pducharme ?

**Comment by domodial** [comment]
I have the big problems with 3.10.1 and there is no tag for 3.9.12 :( Helpppp

**Comment by cwhits** [comment]
`3.9.12` exists now.

**Comment by fryfrog** [comment]
@pducharme nuked the whole automation configuration and re-created it, seems to have fixed it. Yay!
