### ISSUE TITLE
Update for 3.10.1

### ISSUE THREAD

**Issue by mikestecker** [pducharme/UniFi-Video-Controller#125]
Since 3.10.1 is out, could you possibly update?

https://community.ubnt.com/t5/UniFi-Video-Blog/UniFi-Video-3-10-1-Soft-Release/ba-p/2658279

**Comment by fryfrog** [comment]
I just pushed it to `:testing` and `:beta` and I'm running it locally for a bit before pushing to `:latest`.

**Comment by evil-dog** [comment]
Any ETA on pushing 3.10 to :latest?

**Comment by fryfrog** [comment]
Done, hope it works.
