### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by LasseHedeby** [pducharme/UniFi-Video-Controller#131]
Hi

When I create and run this Docker on RPI3 I get this error;
`standard_init_linux.go:207: exec user process caused "exec format error"`

I run with this command;
`docker run \
        --name unifi-video \
        --cap-add SYS_ADMIN \
        --cap-add DAC_READ_SEARCH \
        -p 10001:10001 \
        -p 1935:1935 \
        -p 6666:6666 \
        -p 7080:7080 \
        -p 7442:7442 \
        -p 7443:7443 \
        -p 7444:7444 \
        -p 7445:7445 \
        -p 7446:7446 \
        -p 7447:7447 \
        -v /home/pi/unifi-video/data:/var/lib/unifi-video \
        -v /home/pi/unifi-video/vidoes:/var/lib/unifi-video/videos \
        -e TZ=Europe/Copenhagen \
        -e DEBUG=1 \
        pducharme/unifi-video-controller:latest`

**Comment by fryfrog** [comment]
The `Dockerfile` uses `CMD ["/run.sh"]` now instead of `EXEC`, could it be related to that? I've got a couple Pi3s, I can see what happens when I fire it up. What distro?

**Comment by fryfrog** [comment]
A quick Google suggests that it is because the image isn't for ARM platform.

I don't know of anyone using this on ARM, though I don't know of any reason it *shouldn't* work.

Has it ever?

https://github.com/monicahq/monica/issues/1290
