### ISSUE TITLE
Credentials keep becoming invalid

### ISSUE THREAD

**Issue by bentanvil** [pducharme/UniFi-Video-Controller#134]
I'm not sure if this has something to do with MongoDB but the installation seems to lose all my login credentials. I keep having to reset the installation after a few weeks as all my username and passwords become invalid.

**Comment by phedders** [comment]
Are you mounting a data directory?

**Comment by bentanvil** [comment]
Its a bog-standard Unraid Docker install. The only mounted directories are /mnt/cache/appdata/unifi-video/ mapped to Container Path: /var/lib/unifi-video and /mnt/user/UnfiVideoShareForStorage mapped to Container Path: /var/lib/unifi-video/videos
![Capture](https://user-images.githubusercontent.com/31259336/56237413-0b4c4780-60e0-11e9-83ea-399859ee64ff.PNG)

**Comment by fryfrog** [comment]
I have this problem in my 3.10.1 -> 3.10.2 upgrade, are you running the `:beta` or `:testing` tag?

**Comment by bentanvil** [comment]
No, running stable

**Comment by fryfrog** [comment]
https://community.ubnt.com/t5/UniFi-Video/3-10-1-gt-3-10-2-can-not-log-in/m-p/2765592/highlight/true#M122148

^ Could this be your problem?
