### ISSUE TITLE
URL for .deb not valid in Dockerfile

### ISSUE THREAD

**Issue by gzeel** [pducharme/UniFi-Video-Controller#136]
_I had to change the url for the .deb file from https://dl.ubnt.com/firmwares/unifi-video/v${version}/unifi-video.Ubuntu18.04_amd64.v${version}.deb to https://dl.ubnt.com/firmwares/ufv/v3.10.2/unifi-video.Ubuntu18.04_amd64.v3.10.2.deb to build the docker image..

Looks like Ubiquiti changed their directories.._

Sorry, same as #135

**Comment by fryfrog** [comment]
Fixed, you 3.10.2 is bad. You can get it in `:beta` or `:testing` though, maybe help figure out what is wrong w/ it. :/
