### ISSUE TITLE
Motion detection - Zones - Configure - Fails to load

### ISSUE THREAD

**Issue by pgudge** [pducharme/UniFi-Video-Controller#137]
Clean install of 3.9.12, when I attempt to set the zone area the page fails to load. The preview is a black image, and when clicking it no dots/area selectors appear.

Cameras -> Camera -> Recordings -> Motion Detection -> Zones (Configure)

In the console logs (Chrome) there are various 400 (Bad Request) failures on the api routes.

URL <ip>:7080/api/2.0/snapshot/camera/5cafc0cd4c9474d13a80ae7f?width=182&force=true

All the failed calls return:

_{"rc":"error","message":"api.err.ServiceUnavailable","causedBy":null,"errors":null}_

Looking at logs in docker, I see

==> /var/log/unifi-video/server.log <==
1555700186.607 2019-04-19 18:56:26.607/UTC: WARN   Camera[B4FBE49E4506] Unable to get camera snapshot: Unable to create parent directories of /usr/lib/unifi-video/data/snapshot/B4FBE49E4506/current.jpg in CameraService-TaskExecutor-003

The snapshot folder does not exist in this location. I created it and the camera ID folder, and the page now works fine and snapshots are appearing in the folder.

`# cd /usr/lib/unifi-video/data/`
`# mkdir -p snapshot/B4FBE49E4506/`

**Comment by fryfrog** [comment]
The folder you share in as `/usr/lib/unifi-video/data/` needs to be owned by the `user:group` you run unifi-video as, the error says it was unable to create the parent folder.
