### ISSUE TITLE
Get it working w/o --privileged

### ISSUE THREAD

**Issue by fryfrog** [pducharme/UniFi-Video-Controller#14]
It'd be great to figure out which capability it depends on...

My testing shows it starts up w/ --cap-add DAC_READ_SEARCH, but it didn't show up in video cloud.

**Comment by fryfrog** [comment]
Looks like `--cap-add DAC_READ_SEARCH --cap-add SYS_ADMIN` will do it, I just hadn't waited long enough. Testing locally shows it working nicely.

**Comment by pducharme** [comment]
With the pull now merged, can this be closed?

**Comment by fryfrog** [comment]
Totally. :)

**Comment by tgrosinger** [comment]
I apologize for bumping such an old ticket. Can you please elaborate on why these permissions are required? You can probably imagine my hesitation at running a container with such elevated permissions.
