### ISSUE TITLE
Problem upgrading to 3.10...

### ISSUE THREAD

**Issue by dolphinkite** [pducharme/UniFi-Video-Controller#140]
Bonsoir,

I pulled the 3.10.2 version a few days ago, but when I tried to access it the page would be stuck at the upgrading database page (I go from memory, because now it is stuck at Starting "Unifi video services").

Reading the release notes I now see that I cannot upgrade like I used to... but how can I fix my current installation without losing all my data and having to configure everything all over?

I tried running tag 3.9.12 but that isn't working either. 

I don't care that much about saved video, but ideally I would prefer to keep my current configs (zones, cameras, settings, etc.).

Is there anything I can do to salvage my installation?

Thanks

**Comment by fryfrog** [comment]
They really made upgrading a hot mess. If you're any good at databasing, you can probably do what is needed. The "trick" is to bring up an instance of mongodb w/ your unifi-video db, dump it, create a *new* wiredTiger db, bring up an instance on that *empty* db and then *load* the dumped old db into the new one. But you can also run into issues w/ `featureVersion` depending on the version the DB was for and the version of mongodb you're running.

Its a real hot mess.

Another option is to get it going w/ the version that *worked*, make a backup and then restore that into a clean latest version. This is the route *they* want you to utilize.
