### ISSUE TITLE
Upgrading to 3.10.4

### ISSUE THREAD

**Issue by OddSquirrel** [pducharme/UniFi-Video-Controller#141]
So call me a moron, I'm still trying to get to grips with all that Github/Docker et. al.

I see something about 3.10.4 mentioned and the testing branch on DockerHub seems to be all about that version but nuking the container, downloading testing branch and running it + backup restore seems to end with having the same 3.10.2 I had before. The only difference is that now the backend is telling me that there isn't a new version available.

Does anybody have an idea what I may be doing wrong?

**Comment by ChrisTTian667** [comment]
I think you have to update the package in the container itself, as the container is not updated yet. I'm currently trying the same thing.

**Comment by ChrisTTian667** [comment]
Trying the same thing, with the same result. 

Can someone explain, how we could update the package itself?

**Comment by OddSquirrel** [comment]
@ChrisTTian667 The funny thing is, I noticed it says "3.10.4" in the left column above the link "Alerts" in the main view, but under "Settings" it says "3.10.2". Should be either one or the other, no? 🤔 

![image](https://user-images.githubusercontent.com/39886438/58761358-dedf7400-8543-11e9-9cc9-7c37f2c5371c.png)![image](https://user-images.githubusercontent.com/39886438/58761372-033b5080-8544-11e9-81e1-cd7835a10def.png)

I'm also having trouble logging into the site via video.ui.com, it's mostly stuck at "loading" after selecting the NVR. Works a treat locally, though. The CCTV app on my Apple TV doesn't display video anymore, either.

I guess I'll nuke everything and downgrade to "latest" again until things are wrapped up.

**Comment by ChrisTTian667** [comment]
> @ChrisTTian667 The funny thing is, I noticed it says "3.10.4" in the left column above the link "Alerts" in the main view, but under "Settings" it says "3.10.2". Should be either one or the other, no? 🤔
> 
> ![image](https://user-images.githubusercontent.com/39886438/58761358-dedf7400-8543-11e9-9cc9-7c37f2c5371c.png)![image](https://user-images.githubusercontent.com/39886438/58761372-033b5080-8544-11e9-81e1-cd7835a10def.png)
> 
> I'm also having trouble logging into the site via video.ui.com, it's mostly stuck at "loading" after selecting the NVR. Works a treat locally, though. The CCTV app on my Apple TV doesn't display video anymore, either.
> 
> I guess I'll nuke everything and downgrade to "latest" again until things are wrapped up.

I've downgraded to 3.10.2, but the very exact same problems than yours.
Login doesn't work sometimes. AppleTV App is not showing anything. Timeline is not working at all.

**Comment by OddSquirrel** [comment]
Oh, wow, are you using CCTV Viewer on the TV as well?

And did you downgrade UniFi Video **_and_** the camera firmware? Neither my CCTV Viewer nor UniFi Video would accept the camera until it was back down to 4.10.12 again.

**Comment by ChrisTTian667** [comment]
> Oh, wow, are you using CCTV Viewer on the TV as well?
> 
> And did you downgrade UniFi Video **_and_** the camera firmware? Neither my CCTV Viewer nor UniFi Video would accept the camera until it was back down to 4.10.12 again.

I didn't downgrade the cameras (fw v4.10.12 on all of them). 
But unify video is showing the streams, recording also works. But not the timeline.

**Comment by OddSquirrel** [comment]
Gonna check that out on my end. So are you using CCTV Viewer on the TV?

**Comment by fryfrog** [comment]
Sorry for the delay, I pushed 3.10.4 to the `:latest` tag and created a `:3.10.4` tag too.
