### ISSUE TITLE
need Important Update to 3.10.5

### ISSUE THREAD

**Issue by maestroat** [pducharme/UniFi-Video-Controller#143]
Hello, can you please release the test from 3.10.5, i have done an update from cam, and now the firmware is not compatible with the video controller software.
Camera Status: Disconnected - Firware NotSupported  
UVC G3 Dome  Firmware V4.13.40

Thank you!

**Comment by dvoijen** [comment]
Yes please update

**Comment by maestroat** [comment]
fryfrog Update to v3.10.5. you release this version but i cant update it. say its up to date but i have 3.10.4

i do this 
docker pull pducharme/unifi-video-controller
