### ISSUE TITLE
Update to 3.10.6

### ISSUE THREAD

**Issue by dvoijen** [pducharme/UniFi-Video-Controller#147]
Hi,

Could you please update the image to 3.10.6?

**Comment by brucewillke** [comment]
I attempted a build with this image using 3.10.6 last night.
Upon investigating it seems there is some sort of Mongodb issues.  User can't login, and mongo falls to start cleanly. I didn't investigate too much. But this might be another one of those "backup then restore" updated. 

My guess is pducharme is going to need to do some debugging on this, so 3.10.6 might take a bit to release.

**Comment by brucewillke** [comment]
upgrade notes. beware. lots of known issues
https://community.ui.com/releases/UniFi-Video-3-10-6/4919b9e2-9525-4483-b2f2-53a5b0fc467a

**Comment by anderskvist** [comment]
> Hi,
> 
> Could you please update the image to 3.10.6?

It's out, but be careful - i couldn't login (wrong username/password), so I rolled back to 3.10.5 as I haven't got time to dig deeper into it now...

**Comment by JariInc** [comment]
> > Hi,
> > Could you please update the image to 3.10.6?
> 
> It's out, but be careful - i couldn't login (wrong username/password), so I rolled back to 3.10.5 as I haven't got time to dig deeper into it now...

Same for me, cannot login in 3.10.6.

**Comment by majorvin** [comment]
i guess no news is bad news? :(

**Comment by majorvin** [comment]
I like to help anyone who have this problem. *this will reset your settings and you may lose some data*

1. Under the AppData 
2. Edit system.properties
3. Change ```is_default``` to true *this will reset everything*
4. go to your nvr, ip:7443
5. Restore from back. 
6. Open your backup app data and go to backup folder and import the latest zip file.

**Comment by Elehiggle** [comment]
What the fuck are Ubiquiti doing all the time to break our ability to update without issues? I'm affected as well.

**Comment by fryfrog** [comment]
On the bright side, they're clearly abandoning it in favor of Protect so soon it just won't get *any* updates and we won't have anything to worry about. ;)
