### ISSUE TITLE
Version 3.10.7 still shows as 3.10.6

### ISSUE THREAD

**Issue by fryfrog** [pducharme/UniFi-Video-Controller#153]
I've pushed 3.10.7 to both my own and this `:testing` tag. On my own, it still claims to be version 3.10.6. I've checked the build and the Dockerfile, wiped my local cache and it still has it wrong. Once it builds here, I'll test here...

But in the mean time, if anyone tries it and sees the same thing... let me know.

They're also talking about using mongodb 4.0 finally. :/

**Comment by MrDibbley** [comment]
Rebuild container this morning still show 3.10.6 ? and reports update available?

**Comment by fryfrog** [comment]
3.10.8 has only been pushed to `:testing` and `:beta`, are you using one of those?

**Comment by MrDibbley** [comment]
lol no, just using latest, my bad

Thanks

**Comment by fryfrog** [comment]
I finally updated to 3.10.8 and it shows the version, so mission akomplished.
