### ISSUE TITLE
Can make changes in system configuration

### ISSUE THREAD

**Issue by ahmaddxb** [pducharme/UniFi-Video-Controller#162]
I'm running this docker image on a QNAP NAS and when i try to change setting in the system configuration section I get and error. See attached

I only want to turn on Time Based Purging but there is a problem with the recording path.

![image](https://user-images.githubusercontent.com/43728586/67853883-d6a65780-fb28-11e9-979e-f880e65b0e7b.png)

**Comment by fryfrog** [comment]
That means you don't have permissions correct on the folder you've shared in, correct them. The PUID/PGID you pass in to the container will need to own and have read/write to the volume you pass in.

**Comment by fryfrog** [comment]
Been awhile, I'm assuming you got this figured out.
