### ISSUE TITLE
Upgrade Process

### ISSUE THREAD

**Issue by Kiendeleo** [pducharme/UniFi-Video-Controller#169]
Is there a way to document the upgrade process?

All of my attempts to upgrade the "normal" docker way by stoping and removing the container and starting a new container after a pull result in a broken system.  Even removing the Data folder and restarting from scratch I am having trouble with, with the latest version.  Please help.

**Comment by fryfrog** [comment]
They've made so many breaking changes between versions that I honestly don't know if there is a "right" way to upgrade. There are a few issues here that talk about it, I'd dig through one and see what you find. The TL;DR is that you *probably* need to figure out what your *working* version is doing DB wise (mongodb version and wired tiger vs. whatever the *not* wired tiger is called) and "fix" it for the latest version. Or maybe backup in your working version and then setup the latest version from scratch and restore. It is a total shit show.

**Comment by Kiendeleo** [comment]
I think I found a solution that works, let me outline it.

Enter into the command shell of your docker container: `docker exec -it [Container Name] /bin/bash`
Change to the tmp directory: `cd /tmp`
Download the latest version of the Unifi Video Controller Software: `wget [Insert URL of the latest ubuntu version of the software here]`
Create the patch file: `vi unifi-video.patch`
Copy the patch code from [here](https://github.com/pducharme/UniFi-Video-Controller/blob/master/unifi-video.patch) into the document
Write and close vi: `:wq!`
Stop Unifi Video Server: `service unifi-video stop`
Install the new version: `dpkg -i [Insert filename of Unifi VIdeo Server .deb that you just downloaded]`
Patch the needed files: `patch -N /usr/sbin/unifi-video unifi-video.patch`
Start Unifi Video Server: `service unifi-video start`
Exit out of your docker container: `exit`

This should leave you with an up to date version of the Video Server

I have tested it on one of my servers and it seems to be working fine.

**Comment by fryfrog** [comment]
This isn't a sustainable solution because if your container ever gets deleted, you'll have to do it again. From the other thread, can you see how to show me how the process is running in your *working* container and then in your *not* working container?

**Comment by ianmen** [comment]
I'm facing a similar issue, not even a clean install is working. Always directly routed to the upgrade screen.
