### ISSUE TITLE
Upgrade to 3.10.0 Success but showing 3.9.12 in Other Places

### ISSUE THREAD

**Issue by chihotdog13** [pducharme/UniFi-Video-Controller#171]
I was able to upgrade my docker image to 3.10.0 from 3.9.12. For me, the key was to download the patch, run.sh, and the Dockerfile latest from GitHub. I left my yaml file intact. Also, I renamed the old data folder that is stored in the docker volumes, and when it creates a new one, you get the fresh install. Then, I uploaded my backup I took before upgrading.

However, I am receiving conflicting info: 3.10.10 shows on the main screen above Alerts. But, when I go to Settings, it shows UniFi-Video Controller 3.9.12 above Health Status. Also shows 3.9.12 when I go to settings.

However, the cameras did upgrade their firmware successfully to a supported version on 3.10.10, and everything appears to be working.

Unsure if this is a problem.

**Comment by fryfrog** [comment]
They've done releases in the past that had this problem, see #153 for example. :/

But it sounds like you're doing some crazy stuff in your container? I'd be careful of that, it won't survive an update.
