### ISSUE TITLE
Raspberry 4 - hypriotOS - standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by gpr7700** [pducharme/UniFi-Video-Controller#173]
Hello

on a raspberry 4 (ARM64) we got the error 
standard_init_linux.go:211: exec user process caused "exec format error"

in order to solve the issue I have updated 

FROM phusion/baseimage:0.11
to
FROM phusion/baseimage:master

but then I get

E: Unable to locate package mongodb-org-server
E: Unable to locate package mongodb-org-shell

Regards

Gregory

Regards

**Comment by fryfrog** [comment]
This is an x86_64 only Docker Image. It shouldn't be *too* hard to add aarch64 or armv7h support, but no one has done it yet. Maybe another image has? Maybe you want to figure it out and make it happen? Maybe some day one of us will get around to it?

**Comment by gpr7700** [comment]
Hello
No problem, I will investigate what is wrong and I will let you know when that's working
Regards
