### ISSUE TITLE
Unifi-Video say 3.10.11 is there, but can't update

### ISSUE THREAD

**Issue by tpbillund** [pducharme/UniFi-Video-Controller#175]
Hi
When will the new installer file be on docker.io so I can get the new 3.10.11 there and install ?
It's still the old 3.10.10 thats ther latest on docker.io

Atm. my container is restarting, so it's not working.

I then installed the 3.10.10 again from https://hub.docker.com/r/pducharme/unifi-video-controller and used docker pull pducharme/unifi-video-controller:beta to get the beta downloaded.

Confirmed 
Status: Downloaded newer image for pducharme/unifi-video-controller:beta

But what do I do now, to update from 3.10.10 to 3.10.11 ?

**Comment by fryfrog** [comment]
The `:beta` and `:testing` tags were updated a handful of days ago and thanks to @DerEnderKeks's #174, now `:latest` will be shortly.
