### ISSUE TITLE
Update problem to 3.10.11

### ISSUE THREAD

**Issue by maestroat** [pducharme/UniFi-Video-Controller#177]
Hi, when i will update:
(Reading database ... 13637 files and directories currently installed.)                                                     
Preparing to unpack unifi-video.deb ...                                                                                     
unifi-video: /var/lib/dpkg/info/unifi-video.prerm upgrade 3.10.11                                                           
invoke-rc.d: could not determine current runlevel                                                                           
invoke-rc.d: policy-rc.d denied execution of stop.                                                                          
Installed Version 3.10.10                                                                                                   
unifi-video: /var/lib/dpkg/tmp.ci/preinst upgrade 3.10.10 3.10.11                                                           
..preinst.configure: START                                                                                                  
..preinst.configure DONE!                                                                                                   
Unpacking unifi-video (3.10.11) over (3.10.10) ...                                                                          
unifi-video: /var/lib/dpkg/info/unifi-video.postrm upgrade 3.10.11                                                          
Setting up unifi-video (3.10.11) ...                                                                                        
unifi-video: /var/lib/dpkg/info/unifi-video.postinst configure 3.10.10                                                      
postinst.configre: update /usr/lib/unifi-video/logs symlink to /var/lib/unifi-video/logs                                    
postinst.configure: update /usr/lib/unifi-video/data symlink to /var/lib/unifi-video                                        
invoke-rc.d: could not determine current runlevel                                                                           
invoke-rc.d: policy-rc.d denied execution of start.                                                                         
patch: **** Can't open patch file /unifi-video.patch : No such file or directory

**Comment by fryfrog** [comment]
What `:tag` are you following? What happens if you spin up a new, fresh container instead of updating the existing? What troubleshooting have you done?

**Comment by fryfrog** [comment]
Wait, are you trying to update unifi-video *inside* the container? Are you `docker build`ing this? What is going on? You should be `docker pull`ing to update.
