### ISSUE TITLE
Unable to Manage  - UVC G3 camera

### ISSUE THREAD

**Issue by dtel** [pducharme/UniFi-Video-Controller#180]
Run the Docker container, which does not automatically identtify my camera. When i put the NVR IP directly on the camera, the NVR can detect the camera. However, it gets stuck at managing and nothing happens. Please point me in the right direction.

disabled ufw

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

UBNT Video - v3.10.11
Camera - UVC G3 - v4.18.37

Docker command:
docker run \
        -d \
        --restart=always \
        --name unifi-video \
        --cap-add DAC_READ_SEARCH \
        -p 10001:10001 \
        -p 1935:1935 \
        -p 6666:6666 \
        -p 7080:7080 \
        -p 7442:7442 \
        -p 7443:7443 \
        -p 7444:7444 \
        -p 7445:7445 \
        -p 7446:7446 \
        -p 7447:7447 \
        -v /ubnt/data:/var/lib/unifi-video \
        -v /ubnt/videos:/var/lib/unifi-video/videos \
        --tmpfs /var/cache/unifi-video \
        -e TZ=Europe/London \
        -e PUID=99 \
        -e PGID=100 \
        -e CREATE_TMPFS=no \
        -e DEBUG=1 \
        pducharme/unifi-video-controller

**Comment by dtel** [comment]
Fixed it by adding controller IP & port 7442 as i was doing it remotely and manual configuration.

**Comment by fryfrog** [comment]
Glad you got it sorted out. :)
