### ISSUE TITLE
Recordings eventually stop

### ISSUE THREAD

**Issue by Sprooty** [pducharme/UniFi-Video-Controller#181]
I've had an issue for the last week or so where at some point recordings will just stop occuring.

Logs from the GUI show lots of errors similar to

```
1588155013.185 2020-04-29 10:10:13.185/UTC: ERROR  [uv.recording.svc] [RecordingService] Unable to do emergency shutoff check, shutting off recordings: Mount point for /var/cache/unifi-video/hls not found in RecordingService-EmergencyShutOffCheck

1588155013.184 2020-04-29 10:10:13.184/UTC: ERROR  [uv.recording.svc] [RecordingService] Free disk space has recovered, disabling emergency shutoff in RecordingService-EmergencyShutOffCheck

1588148293.696 2020-04-29 08:18:13.696/UTC: ERROR  [uv.recording.info] Camera[FCECDA30B719] Error starting recorded stream: Unable to create directory for video recording (UVC G3 Micro) in CSTask-05
```

This is the method i am using to launch the container. The underlying disk has ~200gb free, df -h command within the container is showing 200gb free, so it doesn't appear to be a disk space issue.

#
```
docker volume create unifiVideo_data
docker volume create unifiVideo_videos

docker run -d --name=unifVideo --restart always --cap-add DAC_READ_SEARCH -e PUID=99 -e PGID=100 --net=host -v unifiVideo_data:/var/lib/unifi-video -v unifiVideo_videos:/var/lib/unifi-video/videos -e Sydney/Australia  --tmpfs /var/cache/unifi-video -e CREATE_TMPFS=no -e DEBUG=1 pducharme/unifi-video-controller
```

#
Update 1# 
Changing the recording path to /var/lib/unifi-video has removed the errors and it's working ok now. I've removed the mount point for unifiVideo_videos.

Not sure why using a separate volume would be causing issues.

**Comment by thoschworks** [comment]
> Update 1#
> Changing the recording path to /var/lib/unifi-video has removed the errors and it's working ok now. I've removed the mount point for unifiVideo_videos.

Where did you made this change? On the host or in the Unifi-Video-stetting in the container?

**Comment by aspratt** [comment]
@thoschworks changed the mountpoints in my docker run commands. Not using docker compose or compiling manually.

The fix didn't work, i ran into the same issue after about 3 days. I've had to migrate the controller to a non-docker solution.

**Comment by thoschworks** [comment]
You are not alone with this problem (see Issue https://github.com/pducharme/UniFi-Video-Controller/issues/185) 

And I think Issue https://github.com/pducharme/UniFi-Video-Controller/issues/185 was opened because yours was already closed...
