### ISSUE TITLE
Not an Issues but 

### ISSUE THREAD

**Issue by maestroat** [pducharme/UniFi-Video-Controller#182]
Hi, can you make an manual for updating on docker synology? i cant work with the manuals in internet.

**Comment by fryfrog** [comment]
You'll need to research how to update Docker images on Synology. They have have their own GUI and way of doing it.

It might be worth looking at pyouroboros/ouroboros or containrrr/watchtower which are Docker images that allow for automatic updating of running Docker containers.

Good luck.
