### ISSUE TITLE
Can only find camera if "--network="host" \"

### ISSUE THREAD

**Issue by eriklysoe** [pducharme/UniFi-Video-Controller#191]
Hi

The suggested command does not find any camera, but if I remove the ports and use "--network="host" \", camera is found. Not shure what is the problem. Running docker in synology ds916+.

Installs but no camera detected, and not possible to specify ip adress to Unifi-video-controller in camera:
docker run -d \
--name unifi-video \
--cap-add DAC_READ_SEARCH \
-p 10001:10001 \
-p 1935:1935 \
-p 6666:6666 \
-p 7080:7080 \
-p 7442:7442 \
-p 7443:7443 \
-p 7444:7444 \
-p 7445:7445 \
-p 7446:7446 \
-p 7447:7447 \
-v /volume1/docker/unifi-video/data:/var/lib/unifi-video \
-v /volume1/docker/unifi-video/videos:/usr/lib/unifi-video/data/videos \
--tmpfs /var/cache/unifi-video \
-e TZ=Europe/Oslo \
-e PUID=99 \
-e PGID=100 \
-e CREATE_TMPFS=no \
-e DEBUG=1 \
pducharme/unifi-video-controller

This works, and camera finds unifi-video controller:
docker run -d \
--restart=unless-stopped \
--name unifi-video \
--network="host" \
--cap-add DAC_READ_SEARCH \
-v /volume1/docker/unifi-video/data:/var/lib/unifi-video \
-v /volume1/docker/unifi-video/videos:/usr/lib/unifi-video/data/videos \
-e TZ=Europe/Oslo \
-e PUID=99 \
-e PGID=100 \
-e CREATE_TMPFS=no \
-e DEBUG=1 \
pducharme/unifi-video-controller

**Comment by fryfrog** [comment]
It's because they use multicast, I thought the `README.md` mentioned this, but I guess it doesn't or got lost or something. You can use `host` networking to add your cameras, then drop back down to normal after they're added. You can also just tell the cameras what host to connect to.
