### ISSUE TITLE
UniFi Protect cannot discover Video Controller

### ISSUE THREAD

**Issue by svh1985** [pducharme/UniFi-Video-Controller#193]
Hi there,

Is there anything special I need to setup to be able to discover the NVR from the UniFi Protect mobile app?

My Docker compose service:
```
  unifi-video:
    container_name: unifi-video
    restart: unless-stopped
    ports:
     - 10001:10001
     - 1935:1935
     - 6666:6666
     - 7080:7080
     - 7442:7442
     - 7443:7443
     - 7444:7444
     - 7445:7445
     - 7446:7446
     - 7447:7447
    cap_add:
      - DAC_READ_SEARCH
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TIMEZONE}
      CREATE_TMPFS: "no"
      DEBUG: 1
    volumes:
    - ${CONFIGDIR}/unifi-video/data:/var/lib/unifi-video:rw
    - ${CONFIGDIR}/unifi-video/video:/var/lib/unifi-video/videos:rw
    tmpfs:
      - /var/cache/unifi-video
    image: pducharme/unifi-video-controller

```

**Comment by pducharme** [comment]
UniFi protect is a different solution from Ubiquiti.  UniFi Video is the old software that they announce will be retired in couple of months.   They are not working together.  There is no official Linux package available for creating a UniFi Protect docker.  Unfortunately, Ubiquiti reserve the UniFi Protect to owner of UDM Pro or the new UniFi NVR they sell (hardware).

**Comment by thoschworks** [comment]
> Unfortunately, Ubiquiti reserve the UniFi Protect to owner of UDM Pro or the new UniFi NVR they sell (hardware).

I think it also runs on the _Cloud Key Gen2 Plus_ which will be my migration path.
