### ISSUE TITLE
Include a sample systemd unit

### ISSUE THREAD

**Issue by vladionescu** [pducharme/UniFi-Video-Controller#26]
I prefer to manage my containers as systemd units (I haven't figured out yet how to manage the build/upgrade piece). Attached is my unit file for this container. Consider including it in the repo as a sample others can build off of.

For reference, I build this container using this command when in the repo dir `docker build -t unifi-video .` and I name the running container `unifi-video-live`.

**/etc/systemd/system/unifi-video.service**
```/etc/systemd/system/unifi-video.service
[Unit]
Description=UniFi Video Controller (Docker)
Requires=docker.service
After=docker.service

[Service]
Restart=always
ExecStart=/usr/bin/docker run -v /data/docker/unifi-video/data:/var/lib/unifi-video \
			      -v /data/docker/unifi-video/logs:/var/log/unifi-video \
			      -v /data/docker/unifi-video/videos:/usr/lib/unifi-video/data/videos \
			      -p 7080:7080 -p 7443:7443 -p 7445:7445 -p 7446:7446 -p 7447:7447 -p 6666:6666 \
			      --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH \
			      --name=unifi-video-live unifi-video
ExecStop=/usr/bin/docker stop -t 2 unifi-video-live
ExecStopPost=/usr/bin/docker rm -f unifi-video-live

[Install]
WantedBy=multi-user.target
```

Thanks for maintaining this project! Much appreciated 👍

**Comment by fryfrog** [comment]
https://github.com/pducharme/UniFi-Video-Controller/wiki/Startup#systemd

There is one in the wiki, you're suggesting it'd be worth committing that?

Also, instead of your ExecStopPost doing the rm, you can just use `docker run --rm`.

**Comment by vladionescu** [comment]
I didn't notice the one in the wiki, good point. Perhaps it's worth including a note about it in the README.

Thanks for the tip regarding `docker run --rm`, I'll update my unit to do that instead. Makes sense.
