### ISSUE TITLE
New update.. 

### ISSUE THREAD

**Issue by anarro** [pducharme/UniFi-Video-Controller#43]
Hello,

Yesterday Ubiquiti launched a new update, could you update the repository?
Thank you very much for your great work.

Antoni.

**Comment by malle-pietje** [comment]
Correct 3.8.5 is recommended by UBNT and 3.8.4 has been pulled...

**Comment by pducharme** [comment]
Hi Guys, I just updated to 3.8.5.  The Docker is building now.  I'll close the issue now.

**Comment by malle-pietje** [comment]
works like a charm;-)
