### ISSUE TITLE
Configuration Persistance

### ISSUE THREAD

**Issue by 3guk** [pducharme/UniFi-Video-Controller#54]
Just wondering if it would be possible to fix this image so that settings and data persist when you update the docker to the latest version ?

**Comment by mdshw5** [comment]
The settings and data do persist if you pass through the host filesystem like specified in the README:

```
        -v <data dir>:/var/lib/unifi-video \
        -v <videos dir>:/usr/lib/unifi-video/data/videos \
        -v <logs dir>:/var/log/unifi-video \
```

**Comment by 3guk** [comment]
Sorry guys - I posted this to the wrong repo, actually meant to post it to the unifi controller page.
