### ISSUE TITLE
3.9.2 /var/log/unifi-video symlink

### ISSUE THREAD

**Issue by i8beef** [pducharme/UniFi-Video-Controller#58]
Oh another issue I think evil-dog and I both noticed... They moved /var/log/unifi-video under /var/lib/unifi-video/logs instead, and created a symlink between the two. If you have a volume setup to mount that log folder, in 3.9.2 you'd need to remove that so it would write to the new location...

However, they also seem to CREATE that symlink owned by root. As the app runs as the unifi-video user, it doesn't actually seem to have access to traverse this symlink. Not sure if this is your issue, or theirs? But "chown -h unifi-video:unifi-video /var/log/unifi-video" seemed to restore logs writing. This also presents as initial startup getting stuck on "Upgrading" screens, presumably because it fails to start writing logs.

**Comment by fryfrog** [comment]
The change should be the volume pointing at `/var/lib/unifi-video/logs` instead of `/var/log/unifi-video`. This should already have the right permissions, so even if the symlink is owned by `root` it won't matter.

**Comment by fryfrog** [comment]
So now that logs is under the data dir, *should* it be a seperate volume? I kind of thing it doesn't need to be. But it could still be nice? :/

**Comment by fryfrog** [comment]
Addressed by #60 and #61.

**Comment by i8beef** [comment]
Sorry I wasn't clear. Yes, because it is under the data directory now, my assertion was a separate volume was unnecessary. I think you'd still need to do something about the symlink permissions as well, but I'm not clear if this is an upstream issue with Ubiquiti's apt packages, or if its an issue that should be addressed by this Docker image on build.

**Comment by fryfrog** [comment]
You were totally clear, I was just debating with myself weather I'd prefer logs on their own or as part of the data volume.

**Comment by fryfrog** [comment]
I think as long as the ownership of the directories and files is good, the fact the symlink is owned by root doesn't matter. I'll test though.

**Comment by i8beef** [comment]
I think it did for me. I was stuck at the "Upgrading" screen until I changed the symlink permission, but who knows, maybe it was something else that happened to coincide with me changing that.

I'm not sure how Docker handles when you mount a volume whose path exists within another already mounted volume. I'd check that if you add it that way to make sure it doesn't wig out Docker.

**Comment by evil-dog** [comment]
I just built my own version of the image, and with the symlink owned by root everything seems to be working fine.

unifi-video started up and did not get stuck at upgrading.
Logs in the new directory are updating. 

So, I don't think there is a need to fix this in the docker image.

**Comment by fryfrog** [comment]
FWIW, I *can't* update the ownership of a symlink. Maybe I'm doing something wrong, but it was still root:root after doing `chown unifi-video:unifi-video /var/log/unifi-video`.

**Comment by i8beef** [comment]
`chown -h`.

It might not be necessary, I don't know, too much stuff went by this weekend and Im questioning myself now. Just add it to the pile-o-stuff to verify for the next 3.9.2 attempt ;-)

**Comment by fryfrog** [comment]
It doesn't look like this is needed, but we can revisit if someone finds otherwise.
