### ISSUE TITLE
Dockerfile needs updated?

### ISSUE THREAD

**Issue by i8beef** [pducharme/UniFi-Video-Controller#59]
As I was looking into why 3.9.2 was messed up, I noticed a few other things in the Dockerfile:

1. /usr/lib/unifi-video/data/videos isn't listed as a volume
2. Note that eventually for 3.9.2, you'll want to remove the volume reference for /var/log/unifi-video (See #58 about synlink stuff they changed in that version)

Also, there are actual several other ports that are OPTIONAL to expose... not sure if these belong in a Dockerfile because of that, but mentioning that the following need to be exposed if you are using those features might be a good idea, and that they'd need to change if someone remaps them in Unifi Video:

1. 7447 - RTSP (covered already, ignore)
2. 1935 - RTMP restreaming port
3. 7444 - RTMPS restreaming port

**Comment by fryfrog** [comment]
I think I've addressed this in #61, except for the RTMP / RTMPS. What *are* those?

**Comment by i8beef** [comment]
They are streaming protocols that Unifi Video exposes if you turn it on in the settings. As it sits, turning them on in the UI will NOT actually expose them through the Docker image, so you need to go also manually change the ports you are exposing. Not a big deal if documented, but caught me the other day when I was implementing a custom Chromecast stream and couldn't figure out why the RTMP port wasn't accessible.

**Comment by fryfrog** [comment]
Doesn't sound crazy to expose them by default. I'll add it to that pull request.

**Comment by fryfrog** [comment]
This is fixed, though we should flip `/usr/lib/unifi-video/data/videos` to `/var/lib/unifi-video/videos`.
