### ISSUE TITLE
Create a CHANGELOG

### ISSUE THREAD

**Issue by kenperkins** [pducharme/UniFi-Video-Controller#67]
As dependencies start to change or mounts change, etc, it would be great to have a `CHANGELOG` that starts to capture the significant differences between version and what you'll need to do (if anything between them). 

You could even go so far as to version this independently of Unifi Video controller to allow for semver.

**Comment by fryfrog** [comment]
I've been thinking about this off and on over the last few days and... I kind of feel like the commit history is the change log.

**Comment by fryfrog** [comment]
It could also just be part of the `README.md`, maybe?

**Comment by kenperkins** [comment]
I believe that expecting a consumer of a docker container to read through all of the commit history is a bit much. The point of a changelog is to provide that succinctness in such a fashion as to understand the impact, if any, of upgrading from version x to version y. Just my $0.02 though.

**Comment by fryfrog** [comment]
True.

In that case, maybe having it in the README.md would be best so it just shows up right on the front page?

**Comment by kenperkins** [comment]
I don't have a strong opinion on where it should be; this was just an example of one option.

**Comment by fryfrog** [comment]
What do you think of #74?

**Comment by fryfrog** [comment]
This never happened, sorry. :(
