### ISSUE TITLE
No recordings on Unraid

### ISSUE THREAD

**Issue by fss** [pducharme/UniFi-Video-Controller#80]
Since upgrade from 3.9.2 to 3.9.3 I cannot neither access my recordings nor create new ones, possibly user permissions? AFAIK all Unraid dockers are run as root, which logfile shall I tail to provide more info?

**Comment by fryfrog** [comment]
Can you start by posting your `run` command so we can see your volumes and ports and such?

**Comment by fss** [comment]
sorry for not updating this issue, but after digging I came across the comment that user/group has to be set as `unifi-video` which was not needed before (or was applied by the docker itself). nevertheless, I regenerated the whole container with proper folder permissions and now all works like charm.
