### ISSUE TITLE
Unable to connect G3 video cameras to Unifi Controller

### ISSUE THREAD

**Issue by ricardoalmeida123** [pducharme/UniFi-Video-Controller#85]
Hello,

I'm following the instructions for setting up the unifi video controller and connect 2 G3 video cameras and I'm unable to get cameras recognized by the controller. I'm running on a mac mini connected in the same network as the cameras. Tried to generate access token and nothing happens. Apparently, the cameras are unable to connect to my video controller. 
Previous versions were working fine but since firmware upgrade I'm not able to make it work. Both controller and cameras have the last version of their softwares and firmwares.

**Comment by erodewald** [comment]
Same for me. Haven't discovered any useful information to share yet unfortunately.

**Comment by mevatron** [comment]
I believe you have two options here.

1. Run the container with network_mode: "host" within docker-compose (or also --net=host from docker run).
2. Added -p 10001:10001 to the startup so that it can discover devices properly.

If the -p 10001:10001 works for you guys, maybe we should add that to the official docs.

Hope that helps!

**Comment by fryfrog** [comment]
@mevatron, have you confirmed that port 10001 does it?! That would be amazing if it does. I'll add it to my container and see what my test camera does.

**Comment by evilmanic** [comment]
Adding both suggestions from @mevatron worked for me.

**Comment by fryfrog** [comment]
Doing both means you didn't really prove the port mapping worked. :(

**Comment by mevatron** [comment]
@fryfrog I'm only doing the port 10001 mapping and running the container with bridge mode only (not --net=host). It is working properly for me.

**Comment by fryfrog** [comment]
Awesome, added it to the run suggestion :)
