### ISSUE TITLE
setting PUID on Kubernetes pod

### ISSUE THREAD

**Issue by hamzehmohammadnia** [pducharme/UniFi-Video-Controller#89]
Hello,

I've been testing your Dockerfile (pducharme/unifi-video-controller) at DockerHub  to build up my Unifi-nvr controller. But im seeing the logs point at the problem of setting PUID and GUID as follows:

[warn] PUID not defined (via -e PUID), defaulting to '99'
[warn] PGID not defined (via -e PGID), defaulting to '100'
 [info] Permissions already set for volume mappings
mount: permission denied
Starting unifi-video... failed.

Then I have added securityContext: specification to the yaml file that builds pod in kubernetes as:
      securityContext:
          runAsUser: 1000
          fsGroup: 2000

the the logs show:
 [warn] PUID not defined (via -e PUID), defaulting to '99'
I have tried to set the same parameters that you have set within your shell:
PUID="99" , PGID="100" by 
securityContext:
          runAsUser: 99
          fsGroup: 100
but the same result has been yielded and pod gets crashed back off.

Is there any hint about it?

bests,

**Comment by acantril** [comment]
I'm having the same issue. Running on Ubuntu ... via a docker compose file.
  unifivideo:
    container_name: unifi-video
    restart: always
    image: pducharme/unifi-video-controller
    network_mode: "host"
    volumes:
      - /home/$USER/docker_files/unifivideo/data:/var/lib/unifi-video
      - /home/$USER/docker_files/unifivideo/videos:/var/lib/unifi-video/videos
    environment:
      - TZ="Australia/Brisbane"

tried running as various users via -PUID PGID - tried changing the volume permissions on the host to be user 100 group 99 ... same error.

**Comment by acantril** [comment]
The container restarts constantly, so finding it hard to shell in and see the state of the contrainer permissions.

**Comment by mevatron** [comment]
@hamzehmohammadnia @acantril 
Try running the `id` command on Linux or OSX to see your current user's uid and gid pair. You should see something along the lines of

```
uid=1000(yourusername) gid=1000(yourusername) groups=...
```

In this case, you would set PUID to 1000 and PGID to 1000 (change numbers as needed for your setup) and you should be good to go.

Hope that helps!

**Comment by fryfrog** [comment]
This has been open awhile and @hamzehmohammadnia hasn't come back. I think @acantril got resolved in another issue. Closing.
