### ISSUE TITLE
Allow custom TLS certificates

### ISSUE THREAD

**Issue by vladionescu** [pducharme/UniFi-Video-Controller#91]
The [unifi-docker project](https://github.com/jacobalberty/unifi-docker#certificate-support) does a good job of supporting custom TLS certs, notably ones issued by LetsEncrypt.

It'd be great to have the same functionality here. If the NVR software is built similar to the Unifi Controller, perhaps jacobalberty's implementation can be poached.

**Comment by evanrich** [comment]
you could go through kubernetes and have an ingress controller take care of this for you.

**Comment by x-jokay** [comment]
Or even use [traefik](https://hub.docker.com/_/traefik) for all your containers having a web-ui as reverse-proxy with TLS.

**Comment by irvingpop** [comment]
This was pretty easy for me to do manually in this dockerized setup, following the guide here: https://community.ubnt.com/t5/UniFi-Video/Custom-SSL-Certificates-in-3-8-1-and-beyond/m-p/2089043#M88128

I did:

```
docker-compose down

mkdir -p run/data/certificates
openssl x509 -outform der -in /etc/letsencrypt/live/myserver/fullchain.pem -out run/data/certificates/ufv-server.cert.der
openssl pkcs8 -topk8 -inform PEM -outform der -nocrypt -in /etc/letsencrypt/live/myserver/privkey.pem -out run/data/certificates/ufv-server.key.der
chown -R 99 run/data/certificates
rm -f run/data/keystore
rm -f run/data/ufv-truststore

docker-compose up -d
```

**Comment by adamcstephens** [comment]
I got this working too using @irvingpop's steps, though it requires one more

```
grep "ufv.custom.certs.enable=true" run/data/system.properties || ( echo "ufv.custom.certs.enable=true" | sudo tee -a run/data/system.properties )
```

**Comment by ssbarnea** [comment]
Current it seems to be imposible to even use it with an external reverse proxy, see https://github.com/pducharme/UniFi-Video-Controller/issues/148
