### ISSUE TITLE
3.9.7-b1 beta build rtsp regression

### ISSUE THREAD

**Issue by Saik0Shinigami** [pducharme/UniFi-Video-Controller#93]
The current build on the beta channel has an RTSP error that breaks the [raspbian-lite omxplayer monitoring solution](https://community.ubnt.com/t5/UniFi-Video/Tutorial-Raspberry-Pi-3-RTSP-Stream-Viewer/td-p/1536448). 

Per the [patch notes for b2 build](https://community.ubnt.com/t5/UniFi-Video-Beta-Blog/UniFi-Video-3-9-7-Beta-2-Release/ba-p/2375590) the RTSP error has been resolved. Can we get an updated beta build here for those of us having issues with beta 1 but want to test the beta builds for our synology-based systems?

**Comment by fryfrog** [comment]
Whoops, sorry for not noticing! I just pushed the final 3.9.7 to beta and will to latest shortly.

**Comment by Saik0Shinigami** [comment]
Don't be sorry, that was an hour turnaround and I applaud it. Thanks for the work, I appreciate it.

**Comment by fryfrog** [comment]
Oh, ha! I assumed it had been open for ages w/o actually checking! :)
