### ISSUE TITLE
/usr/lib/unifi-video vs /var/lib/unifi-video

### ISSUE THREAD

**Issue by depasseg** [pducharme/UniFi-Video-Controller#99]
In the docker run command it looks like external storage is being mapped to /var/lib/unifi-video (and videos).  But when opening the system configuration in the Unifi Video webgui, the default recording location is /usr/lib/unifi-video/videos.  Should the mapping be changed?

**Comment by fryfrog** [comment]
They do crazy symlinking in the package. It is so ugly. But I want to avoid stacking changes on their weirdness.

Hopefully their new Unifi Protect is better done.
